Avoid empty locations tree leaf
gradle/configuration-cache-report pull request #25
Opened 2024-08-06 14:19 UTC by reinsch82

2024-08-07 12:09 UTC, hegyibalint approved these changes
Looks proper to my (untrained) eye.

2024-08-07 13:10 UTC, donat requested changes
Looks good; let's discuss one aspect.

2024-08-07 13:10 UTC, donat commented on src/jsMain/kotlin/problemReport/InitProblemReportModel.kt
> +    }
❌ IIUC you dynamically calculate what should be the default tab based on the content. I think we should not do that. As a user frequently opening the same report, it can be quite confusing to see a completely different tab by default when the build start to produce different problem reports.

2024-08-07 13:31 UTC, bamboo commented on src/jsMain/kotlin/problemReport/InitProblemReportModel.kt
> +    }
AFAIK, we've always been using that strategy (opening on the first tab that has useful information) to optimize the experience based on our best judgement about the usefulness of the information and nobody complained.

2024-08-07 13:42 UTC, reinsch82 commented on src/jsMain/kotlin/problemReport/InitProblemReportModel.kt
> +    }
In the first try on the gradle/gradle build I had an empty file location tab.
I still think it is the most useful tab, but when it is empty it is not useful at all.

2024-08-07 14:08 UTC, donat commented on src/jsMain/kotlin/problemReport/InitProblemReportModel.kt
> +    }
I gave it a second thought. In most cases we will have file locations associated with the problem reports, so the default tab will be mostly the same. I still think it's a bit confusing to see a different default tab in rare occasions, but I'm not completely against this change.

2024-08-07 14:08 UTC, donat approved these changes

2024-08-07 16:06 UTC, merged

2024-08-08 08:52 UTC, alllex commented on gradle.properties
> +configuration-cache-report.version=1.11
We should separate the PRs, changing the implementation with changes required to release another version of the report. Releasing the report should be followed by bumping the version to the next snapshot. Currently, the `main` is not on a snapshot version